/// Orders, line items, documents, checkout settings, and request models.
///
/// Import this library as `order` alongside `package:inttegro/inttegro.dart`.
library;

import 'src/serialization.dart';
import 'checkout.dart' as inttegro_checkout;
import 'inttegro.dart' as core;
import 'customer.dart' as inttegro_customer;
import 'money.dart' as inttegro_money;
import 'payment.dart' as inttegro_payment;
import 'payment_method.dart' as inttegro_payment_method;
import 'price.dart' as inttegro_price;
import 'product.dart' as inttegro_product;
import 'refund.dart' as inttegro_refund;
import 'shared.dart' as inttegro_shared;
import 'wallet.dart' as inttegro_wallet;

part 'src/order/address.dart';
part 'src/order/cancel_request.dart';
part 'src/order/checkout_settings.dart';
part 'src/order/complete_request.dart';
part 'src/order/create_existing_customer_input.dart';
part 'src/order/create_existing_customer_input_checkout_settings.dart';
part 'src/order/create_existing_customer_input_request_meta.dart';
part 'src/order/create_new_customer_input.dart';
part 'src/order/create_new_customer_input_checkout_settings.dart';
part 'src/order/create_new_customer_input_request_meta.dart';
part 'src/order/create_request.dart';
part 'src/order/created_from.dart';
part 'src/order/created_from_resource_type.dart';
part 'src/order/customer.dart';
part 'src/order/discount.dart';
part 'src/order/discount_line_item.dart';
part 'src/order/discount_line_item_variant.dart';
part 'src/order/document_delivery.dart';
part 'src/order/document_delivery_attempt.dart';
part 'src/order/document_delivery_failure.dart';
part 'src/order/document_delivery_request.dart';
part 'src/order/document_delivery_result.dart';
part 'src/order/document_format.dart';
part 'src/order/document_kind.dart';
part 'src/order/existing_customer_create_request.dart';
part 'src/order/fee_details_input.dart';
part 'src/order/fee_line_item.dart';
part 'src/order/fee_line_item_fee.dart';
part 'src/order/fee_line_item_input.dart';
part 'src/order/fee_line_item_input_variant.dart';
part 'src/order/fee_line_item_variant.dart';
part 'src/order/finalize_request.dart';
part 'src/order/invoice.dart';
part 'src/order/invoice_format.dart';
part 'src/order/line_item.dart';
part 'src/order/line_item_group.dart';
part 'src/order/line_item_input.dart';
part 'src/order/line_item_type.dart';
part 'src/order/lookup_request.dart';
part 'src/order/new_customer_create_request.dart';
part 'src/order/order.dart';
part 'src/order/page.dart';
part 'src/order/page_request.dart';
part 'src/order/pay_request.dart';
part 'src/order/payout_settings_request.dart';
part 'src/order/payout_settings_request_destination.dart';
part 'src/order/product_line_item.dart';
part 'src/order/product_line_item_input_variant.dart';
part 'src/order/product_line_item_product.dart';
part 'src/order/product_line_item_variant.dart';
part 'src/order/receipt.dart';
part 'src/order/receipt_format.dart';
part 'src/order/request_confirmation_request.dart';
part 'src/order/shipping_input.dart';
part 'src/order/shipping_line_item.dart';
part 'src/order/shipping_line_item_input.dart';
part 'src/order/shipping_line_item_input_variant.dart';
part 'src/order/shipping_line_item_shipping.dart';
part 'src/order/shipping_line_item_variant.dart';
part 'src/order/status.dart';
part 'src/order/update_request.dart';
part 'src/order/update_request_payment_method_data.dart';
part 'src/order/update_request_payment_method_data_mobile_money.dart';
